name: Deploy React App
on: workflow_dispatch
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      # - name: Get the repository code
      #   uses: actions/checkout@v3
      # - name: Install dependecies
      #   run: npm ci
      # - name: Test app
      #   run: npm run test
          run: echo Testing...
  lint: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint app
        run: npm run lint
  build: 
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint app
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploying...
