name: Deploy React App witn one steps Block
on: workflow_dispatch
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
        run: echo Testing...
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint app
        run: npm run lint
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint app
        run: npm run build
      - run: echo Deploying...