name: Print Pull Request Context
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopen]
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*' 
jobs: 
  print:
      runs-on: ubuntu-latest
      steps:
        - name: Print context
          run: echo "${{ toJSON(github.event) }}"
